export { default as Carousel } from './carousel/Carousel';
export { Features } from './features';
export { RecentlyArrived } from './recently-arrived';
export { OrderNow } from './order-now';
export { CustomerExperience } from './customer-exerience';
export { FeaturedProducts } from './featured-products';
export { BestSeller } from './best-seller';
export { Subscribe } from './subscribe';
export { OverRated } from './over-rated';
export { Categories } from './categories';
