version: '3'

services:
  totplatform-website-env-testing:
    build:
      context: ../../
      dockerfile: docker/testing/Dockerfile
    image: totplatform-website-env-testing
    env_file:
      - ../../.env.test
    ports:
      - ${TOTPLATFORM_WEBSITE_TESTING_EXPOSED_PORT}:8092
